spring:
  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    open-in-view: false

  # DB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
 # flyway
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
